### ISSUE TITLE
Alphabet classification seems off

### ISSUE THREAD

**Issue by RolfKal** [swex/QR-Image-embedded#11]
In the IsAlphabetData() there is a check for the character to be between '0' and '9'.

This seems odd as that check is already done in IsNumeralData() but the lower case letters 'a' tp 'z' are never tested and end up falling in the 8bit data class.

Shouldn't this:

    int IsAlphabetData(unsigned char c)
    {
        if (c >= '0' && c <= '9')
            return 1;

be instead: 

    int IsAlphabetData(unsigned char c)
    {
        if (c >= 'a' && c <= 'z')
            return 1;

**Comment by swex** [comment]
no, its special alphabet from qr standard.
