### ISSUE TITLE
README.md mis-describes "version" parameter

### ISSUE THREAD

**Issue by charliebruce** [swex/QR-Image-embedded#13]
In the README, it states

`(int) version: One of QR_VERSION_{S,M,L}.`

but as far as I can tell, EncodeData actually expects version to be the QR code version (in the range 1-40)  not the version group - have I misunderstood the parameter, or is this a mistake in the README? Alternatively, should QR_VERSION_{S,M,L}. be defined as either {10,27,40} or {9,26,39}, not {0,1,2}?

**Comment by swex** [comment]
fixed
